### ISSUE TITLE
POST request specs missing in rendered docs

### ISSUE THREAD

**Issue by ptdel** [sphinx-contrib/openapi#38]
Running the provided example documentation at https://sphinxcontrib-openapi.readthedocs.io/#how-to-use
```
    post:
      summary: Create an Evidence
      description: |
        Creates a new evidence record in database.
      parameters:
        - name: evidence
          in: body
          schema:
            $ref: '#/definitions/Evidence'
      responses:
        201:
          description: An evidence.
          schema:
            $ref: '#/definitions/Evidence'
```
renders as:
![2019-03-13-094430_3000x1920_scrot](https://user-images.githubusercontent.com/5721307/54283757-0c380980-4575-11e9-86b3-943d8869b7bb.jpg)

I was also unable to get any description of the body in my own api specs using a `parameter:` block with `in: body`, or with the openapi 3.0 `requestBody:` block.  Is there anything I need to configure in order for rendered docs to display a spec of the request body for POST requests?  If this is intended let me know, I'm relatively new to writing openapi docs

**Comment by albert2126** [comment]
This pull request resolves it:
Request body is missing in rendered docs  #47:
https://github.com/sphinx-contrib/openapi/pull/47

**Comment by ikalnytskyi** [comment]
I asked this in #47, but I'll repeat this question here too. Is this ticket about what's called [`:examples:`](https://sphinxcontrib-openapi.readthedocs.io/#options) on our docs? Because it looks so. `:examples:` actuall generates an example snippet based on `requestBody`. It's turned off by default because in my opinion, it does too much and lacks some testing. I'm going to work on this and improve it in near future.

**Comment by ptdel** [comment]
@ikalnytskyi Yes, at the time I was unable to get any sort of schema to render via any of the methods in the issue in either the example or just some other yaml spec.  Sorry it's been a little bit so it's not as fresh in my mind now.  I can understand not wanting to re-create functionality. However, if @albert2126 has a PR that has high test coverage that fits in form and factor with the existing codebase is there any reason that this can't be merged in, with the untested functionality being removed/replaced?

**Comment by ikalnytskyi** [comment]
I never said it was untested. I said it lacks some tests. You see, the *examples* functionality is better and worse at the same time. It's better because it does not blindly shows you a schema. Instead, it tries to produce and show a valid payload with fake data. It's worse because such functionality has a bunch of nuances, such as different combination of types and formats, etc. What I'm saying is that I'm not quite sure we covered all possible invariants. It works great on all *samples* specs I tested, yet, I'm not that confident that it works for all the cases, that's why it's turned off by default.

**Comment by ptdel** [comment]
Only my opinion, but I would prefer that a renderer did simply return the schema blindly to me.  I would think that the functionality of dynamically injecting mock data to a produced schema would be outside the scope of producing the schema, and more suited for an extension or external method of some sort.  If this PR implements the simple functionality of producing a valid request body, I would still ask if there are any reasons that it could not be merged. As the saying goes, a bird in the hand is worth two in the bush.

We've had to move on from using the extension as it stands, but it would certainly make life easier to be able to utilize it again if it's rendering is comprehensive.

**Comment by ikalnytskyi** [comment]
> I would still ask if there are any reasons that it could not be merged. 

Yes, there are. Here's an incomplete list if you are interested:

* No tests. Not even a single one.
* Code duplication.
* Hardcoded values of `Host` and `Content-Type` in rendered HTTP *example* (while in fact it's not even an **example**, but **schema**).
* Bad assumption that a body contains only `application/json` content that crashes with any other `Content-Type` value.

Besides, I still do not understand why are you so oppose using `:examples:` option? Does it break some use case for you? Can you please elaborate on this? Because I finally found some time to work on this, and your use case may help me to understand better what's broken and how can I fix it.

**Comment by albert2126** [comment]
Thank you guys for the discussion.

As a matter of a fact, an example is not enough in most cases because it often does not show all properties that can be used in a POST or PUT request. This makes a developer to open the YAML file to find the full specification on the required request.
The proposed update doesn't touch the example section. It just adds the request body section.
This is how Swagger-UI does.

I'm studying your notes above to improve the code.
Thanks,
Albert

**Comment by ptdel** [comment]
@ikalnytskyi Thanks for the explanation, gotta have tests :slightly_smiling_face: .  The issue was created in regards to other keywords that were not rendering properly in the spec, I don't have any particular issue with `examples:`

@albert2126 I would take a look at writing tests in [pytest](https://docs.pytest.org/en/latest/) and [tox](https://tox.readthedocs.io/en/latest/).  Most folks will want code coverage included in PRs.  I'd also recommend reading up on [TDD](https://en.wikipedia.org/wiki/Test-driven_development#Test-driven_development_cycle).  You're on the right track

**Comment by albert2126** [comment]
@ptdel Thanks a lot for your support. I've added the new option ":request:" to the test_openapi3_success() function. 
Let me know guys if I did something wrong. :)

**Comment by albert2126** [comment]
I'm working as an API documentator, so I know that the Request Body section is absolutely necessary. Otherwise PUT and POST method descriptions are incomplete.

I hope also that someone will make long sections (examples and request/response body) collapsible. 
In my documents, I can make the whole "openapi" admonition section collapsible, but it would be nice to have the same possible for the sections inside that admonition.

**Comment by lilisha100** [comment]
Has this been fixed? I just downloaded and installed package, and did a build. I didn't get any POST request body rendered.

**Comment by albert2126** [comment]
Hi @lilisha100,

Yes it works if you add the :request: option there. The POST request body is not shown by default for backward-compatibility purpose.
This is an example that I just tested on sphinxcontrib-openapi version 0.5.0:

.. openapi:: ../../schemas/cmp.json
   :paths:
      /customers
   :request:
   :examples:

When build, the document displays both, the POST request and examples.

Unfortunately, this option is missing in the documentation.

**Comment by PabloSanchez95** [comment]
Hi @albert2126 ,

I've tried the :request: option and it works but gives me a warning `rst:24: WARNING: Explicit markup ends without a blank line; unexpected unindent.` But I don't have that many lines.

My rst is as follow:
`
.. openapi:: /openapi/auth.yml
   :request:
`
Is there any way to get rid of the warning?

**Comment by PabloSanchez95** [comment]
Hi @albert2126 ,

I've tried the :request: option and it works but gives me a warning `rst:24: WARNING: Explicit markup ends without a blank line; unexpected unindent.` But I don't have that many lines.

My rst is as follows:
``` rest
.. openapi:: ../../schemas/cmp.json
   :request:
```
Is there any way to get rid of the warning?

**Comment by albert2126** [comment]
Hi @PabloSanchez95 PabloSanchez95,

In reST such cases are common. Ensure that you have an empty line after the markup block. Try to use spaces instead of the tab before ":request:".
