### ISSUE TITLE
setuptools as runtime requirement?

### ISSUE THREAD

**Issue by carlodri** [sphinx-contrib/openapi#60]
I'm not quite sure but from here:

https://github.com/sphinx-contrib/openapi/blob/399051211f8442f32e2ddbaeda99fc3a13ef7c20/sphinxcontrib/__init__.py#L12

it seems like `setuptools` (`_scm`?) should also be a runtime requirement. What am I missing here?

I maintain the [conda-forge feedstock for this package](https://github.com/conda-forge/sphinxcontrib-openapi-feedstock/pull/2) and it seems that CI fails white testing a basic `import sphinxcontrib.openapi` due to missing `pkg_resources`. Any hint?

Thanks!

**Comment by ikalnytskyi** [comment]
@carlodri I'm sorry for ignoring your question so long. I'm not sure whether your question is still open. But let me answer on this.

`pkg_resources` is distributed along with `setuptools`. While it may look bizarre, many Python packages  use `pkg_resources` to retrieve and show currently installed version of the package.

The line you're referring to is the pattern established in sphinxcontrib world to define a namespace. Even if I remove this line from this package, the CI will still fail because this line exists in the package I rely on. So long story short, unfortunately setuptools indeed needs to be a runtime requirement.

**Comment by carlodri** [comment]
thanks @ikalnytskyi, indeed it seems like it was some glitch in conda...
